### ISSUE TITLE
Error: Cannot find module './HDNode.js'

### ISSUE THREAD

**Issue by dalbelap** [BitGo/bitgo-recovery-tool#1]
In file src/recoveryTool.js, line 11:
var HDNode = require('./HDNode.js');

It should be:
 var HDNode = require('./hdnode.js');

or rename hdnode.js to HDNode.js

**Comment by masonicGIT** [comment]
Hey @dalbelap,

Thanks for opening this issue, would you be able to let us know what OS and version you ran this on?

**Comment by dalbelap** [comment]
GNU/Linux Debian

**Comment by masonicGIT** [comment]
Fixed in commit: 434407cf82dfb611dafc7497c55fc265e43e5af6.

Thanks :)
